version: '3.8'

services:
  api-csv-handler:
    container_name: api-csv-handler
    build: ./app
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/usr/src/app/app