POST http://localhost:8080/api/v1/bills/import
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="bills.csv"

< ./bills.csv
--WebAppBoundary--

###

POST http://localhost:8080/api/v1/bills/export
Accept: application/json
Content-Type: application/json

{
  "client_org": "OOO Client1Org5"
}

###

{
  "client_name": "client2",
  "client_org": "OOO Client2Org1"
}